# Generated by Django 5.0.6 on 2024-05-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_cities_city_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(default=None, upload_to='city_images/'),
            preserve_default=False,
        ),
    ]
