# Generated by Django 5.0.6 on 2024-05-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_city_latitude_city_longitude_alter_city_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='city',
            name='longitude',
        ),
    ]
